name = "PSDMatrices"
uuid = "fe68d972-6fd8-4755-bdf0-97d4c54cefdc"
authors = ["Nathanael Bosch <nathanael.bosch@gmail.com> and contributors"]
version = "0.4.7"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"

[compat]
PDMats = "0.11.30"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
