name = "PSDMatrices"
uuid = "fe68d972-6fd8-4755-bdf0-97d4c54cefdc"
authors = ["Nathanael Bosch <nathanael.bosch@gmail.com> and contributors"]
version = "0.4.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6,1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
